version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "iabdulwahab82"
      DB_MYSQL_PASSWORD: "Hamradio@1982"
      DB_MYSQL_NAME: "iabdulwahab82"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
  db:
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'Hamradio@1982'
      MYSQL_DATABASE: 'iabdulwahab82'
      MYSQL_USER: 'iabdulwahab82'
      MYSQL_PASSWORD: 'Hamradio@1982'
    volumes:
      - ./data/mysql:/var/lib/mysql